### ISSUE TITLE
Question: how does the data checking work?

### ISSUE THREAD

**Issue by navaru** [manuelstofer/pflock#1]
How does the data checking work? Is it similar to Angular's dirty checking?

Why did you choose to this syntax: x-bind="attr:.prop.prop" ?

I am learning two way data binding, I am not asking as a critique question.

**Comment by manuelstofer** [comment]
Dirty checking is not implemented at all. You need to call toDocument manually, which
will write all bound values to the DOM. 

Here is an example:

``` Javascript
var pflock = require('pflock');
var data = {name: 'foo'};
var bindings = pflock(document.body, data);

data.name = 'bar';

// must be called manually
bindings.toDocument();
```

I want to keep it very simple and limit the scope of Pflock to write values to the DOM, listen to DOM events and push changed data back to the original data structure. Its not intended to become a framework like Angular.

If you want data to be written automatically you could use Backbone models or something similar and listen for change events.

Pflock is in a very initial stage so things might change. Specially the binding Syntax. The main drawback is that currently only one attribute, the value or the innerHTML of an DOM element can be bound. For Example its currently not possible to bind the alt and the src attribute of an img tag. Suggestions to improve the binding syntax are very welcome!

**Comment by manuelstofer** [comment]
There is now an adapter to use Pflock with Backbone models:
https://github.com/manuelstofer/backbone-pflock

**Comment by manuelstofer** [comment]
I removed the unnecessary dot in the binding syntax. It looks now like this: x-bind="attr:prop.prop"
