### ISSUE TITLE
Doesn't pass pointer, value on changed event

### ISSUE THREAD

**Issue by CharlotteGore** [manuelstofer/pflock#12]
I've been trying to use the backbone-pflock module, but it crashes out because it's attempting to read the value of pointer and value that it expects from binding.on('changed') but pflock actually sends no value at all. It's merely a notification that it's changed, which means the model.set(path, value) cannot work either.

I've raised the issue here because the Readme.md for pflock suggests that on('changed') **should** be getting a pointer and value, so I'm not sure if this is expected behaviour.

**Comment by manuelstofer** [comment]
Sorry for the late answer. This is definitely an issue. I hope will find time tomorrow to fix it.

on('changed') will not have the path, value arguments any more, the documentation is not up to date.
I changed this so other scripts can make multiple dom changes and then emit a 'read' event on any
dom node. Pflock will read all changes and trigger 'changed' just once.

I will add an other event that triggers for each change and provides path and value.

**Comment by CharlotteGore** [comment]
Great, thank you :)

**Comment by manuelstofer** [comment]
There is now a new event `path-changed` that receives the path + value

**Comment by manuelstofer** [comment]
I updated backbone-pflock to support the current version of pflock.

**Comment by CharlotteGore** [comment]
Hey, thanks :)
