### ISSUE TITLE
Data Array

### ISSUE THREAD

**Issue by t8g** [manuelstofer/pflock#4]
How about dealing with data arrays ?

``` javascript

var data = {
    users: [
        { name: 'Douglas' },
        { name: 'Abraham' }
    ]
}
```

And something like this : 

``` html
<ul x-bind="each:users">
  <li x-bind=".name"></li>
</ul>
```

That could be replaced by 

``` html
<ul x-bind="each:users">
  <li x-bind="users.1.name">Douglas</li>
  <li x-bind="users.2.name">Abraham</li>
</ul>
```

**Comment by manuelstofer** [comment]
I will think about that. I planed to handle this in the templating. For this purpose i created a very simple [template engine](https://github.com/manuelstofer/richardparker) that makes it easy to create the bindings.

Template:

``` html
<ul>
  {each users
    <li x-bind="{path name}">{. name}</li>
  }
</ul>
```

Will produce something like this:

``` html
<ul>
  <li x-bind="users.0.name">Douglas</li>
  <li x-bind="users.1.name">Abraham</li>
</ul>
```

This does not handle inserted / removed items of the array. But you can just re-render it. Pflock only adds event listeners to the specified root element so its save to just replace the inner html.

What do you think about the template approach?

**Comment by t8g** [comment]
Yes I've seen you're template engine, but it would be so cool if the binding could also work with arrays :)
I'm working on it and I hope be able to send you a pull request tomorrow.

The only problem I've got right now is how to remember the inner html (sort of template) once it has been rendered.

Only 20 LOC, for the moment :)

**Comment by manuelstofer** [comment]
Im excited to see your pull request.

It would be cool if this works without a template engine! And i think what you want to do is a great Feature!
Until now Pflock just reads and writes values of the DOM. Im not 100% sure if it should be in the scope of Pflock to do structural changes. What do you think if we would let Pflock emit custom DOM events when the data of an array changes?

Something like this:

``` html
<ul x-bind-data-change="users">
  <li x-bind="users.1.name">Douglas</li>
  <li x-bind="users.2.name">Abraham</li>
</ul>
```

If data.users changes Pflock would trigger a 'data-changed' event to the UL element with the new data. So it could be handled from there. This way we can keep it template language agnostic.

**Comment by manuelstofer** [comment]
Actually i think we should do both! So it can be handled with the proposed each syntax or by rerendering with a template engine. 

I'm happy you are contributing to Pflock!

**Comment by manuelstofer** [comment]
I think the easiest way is to store the inner html (template) on the dom element.

**Comment by t8g** [comment]
Where in the dom could I store the inner html ?
Inside a new attribute ? The template can be big !
Or as hidden child, but what if there is further dom manipulation (like counting or sorting the children).

**Comment by manuelstofer** [comment]
Pull request is merged and x-each is supported now, so i'm going to close this now.
