### ISSUE TITLE
Date error

### ISSUE THREAD

**Issue by t8g** [manuelstofer/pflock#6]
No output of date

For example : 

``` javascript
var data = { "mydate": new Date() };
```

``` html
<span x-bind="mydate"></span>
```

Seems to be a problem in the toPathValueHash and isIterable functions : obj === Object(obj) for a date return true;

Maybe a workaround in using  : Object.prototype.toString.call(obj) === '[object Object]'

**Comment by manuelstofer** [comment]
Yes thats a Bug. I think your workaround should do fine.
We also use [is](https://github.com/manuelstofer/is) to test: is.array(obj) || is.object(obj)

I will do a bugfix after work.
