### ISSUE TITLE
Add filter options

### ISSUE THREAD

**Issue by t8g** [manuelstofer/pflock#7]
Maybe something like 

``` html
<span x-bind="name|lowercase"></span>
```

**Comment by manuelstofer** [comment]
I think this is a good idea. But it should be reversibe. What do you think about following?

``` html
<span x-bind="birthday" x-write-filter="formatDate" x-read-filter="parseDate">
```

If we us separate x- attributes it can be implemented as plugin instead of integrating it to x-bind.

**Comment by t8g** [comment]
+1 for separate attribute, but I can't see the real benefit of having two of them. What is the concrete usage for x-read-filter ?

**Comment by manuelstofer** [comment]
With a date you might want to have a localized format depending on the users language/region. So you need to convert it back to the original format.
x-read-filter could also be used to convert something back to an object. In this case to a Date object.

**Comment by t8g** [comment]
Got it !

More useful for inputs, that's it ?

``` html
<input x-bind="birthday" x-write-filter="formatDate" x-read-filter="parseDate">
```

With Date object for birthday will output a nice formated date thanks to formatDate and if the user change the input, this input will be transformed in Date object ! 

Great !
